### ISSUE TITLE
readBool maxASDULen should be ‘1’ ?，now is ‘0’

### ISSUE THREAD

**Issue by cea5** [calimero-project/calimero-core#109]
![image](https://user-images.githubusercontent.com/17960530/159648667-03eb46bf-93cc-40ac-a4e7-309fb6019aab.png)
![image](https://user-images.githubusercontent.com/17960530/159648768-d957428f-4bd0-4455-af91-093dc473ecfd.png)
I read the kxn specification, but can't find anything about len limit of DPTXlatorBoolean. But in real project, i encountered two points illustrated above which is captured by wireshark. These DPTXlatorBoolean points have disfferent length. So i changed the maxASDULen to 1, and  it turns out to be right. Am I right?
![image](https://user-images.githubusercontent.com/17960530/159651255-c23c3785-5be8-40a5-a4e4-140664345b8d.png)

**Comment by bmalinowsky** [comment]
KNX booleans don't have different lengths, so this is not correct.
