### ISSUE TITLE
DPT 7.003 and 7.004 unit

### ISSUE THREAD

**Issue by holgerfriedrich** [calimero-project/calimero-core#128]
It seems that DPT 7.003 and 7.004 have unit "ms" in the spec, although the example range is given in seconds.

Calimero uses "ms" for DPT 7.002, and "s" for 7.003 and 7.004.

Proposal to change to "ms" and adapt the boundary as well.

Please feel free to close this issue if you think this should not be changed.

**Comment by bmalinowsky** [comment]
Yes, it makes sense to go with the unit as specified in the dedicated column, and not the unit used for specifying the range.

**Comment by bmalinowsky** [comment]
@holgerfriedrich FYI, this will also likely affect DPT 243.600, which uses 7.004, and is currently in [s].

**Comment by holgerfriedrich** [comment]
@bmalinowsky just checkd my unit tests, time component of 243.600 seems to be fine.

**Comment by bmalinowsky** [comment]
@holgerfriedrich thanks for for reports!
