### ISSUE TITLE
发现服务是不是我用的方法不对

### ISSUE THREAD

**Issue by bert1020** [calimero-project/calimero-core#131]
我每次搜索完成之后,我的理解是搜索时创建的socket连接应该关闭的,但事实上却没有关闭.

我的场景是 每10秒重新去发现一次所有服务,以便中途接通的服务也可以被发现

我这样写之后,socket连接一直在增加,,没有关闭

**Comment by bert1020** [comment]
thanks

**Comment by bmalinowsky** [comment]
Which version are you currently using? Snapshots?

**Comment by bert1020** [comment]
`<dependency>
            <groupId>io.calimero</groupId>
            <artifactId>calimero-core</artifactId>
            <version>3.0-SNAPSHOT</version>
        </dependency>`
用的是这个版本

**Comment by bmalinowsky** [comment]
The discoverer in the snapshot build should now close its selector and channel during `quit`, so successive socket creation should not be an issue anymore. Thanks for noticing!

**Comment by bert1020** [comment]
thanks
