### ISSUE TITLE
Awaiting 2.3 release ...

### ISSUE THREAD

**Issue by tuxedo0801** [calimero-project/calimero-core#31]
In reference to issue #28 --> Is there any update on this? Will the release come this year?

**Comment by tuxedo0801** [comment]
*ping* @bmalinowsky ...

**Comment by tuxedo0801** [comment]
Is this project kind of dead?!

**Comment by bmalinowsky** [comment]
> Is this project kind of dead?!

It's kind of not?!

**Comment by tuxedo0801** [comment]
So, if it's not dead ;-) Any ideas about the 2.3 release date?!

**Comment by bmalinowsky** [comment]
There will be a beta before, some days from now. Reason being that accounting for repeated .inds with TP-UART does affect execution time in some cases (might trigger timeouts and degrade performance). Release depends on a reasonable fix for that.

**Comment by bmalinowsky** [comment]
... and when i replace a siemens relay that melted half the TP lab setup

**Comment by tuxedo0801** [comment]
Thanks for the update, will look forward to the beta.

**Comment by calimero-project** [comment]
v2.3-beta done. Please open a new issue for the beta where necessary.
