### ISSUE TITLE
Communication blocked for 255 telegrams  once Calimero rcv-seq behind 

### ISSUE THREAD

**Issue by Kusig** [calimero-project/calimero-core#39]
Communication is blocked for the next 255 telegrams if the Calimero counter somehow is behind the received seq-ctr.

See discussion at:  https://sourceforge.net/p/calimero/discussion/485103/thread/7204e4d1/

**Comment by bmalinowsky** [comment]
v2.3 can now re-sync to the sender sequence in case of a _single_ loss. It is opt-in behavior using the system property `calimero.knxnetip.tunneling.resyncSkippedRcvSeq`, e.g., on the command line: `-Dcalimero.knxnetip.tunneling.resyncSkippedRcvSeq`.
