### ISSUE TITLE
calimero 2.4 no LogManager anymore

### ISSUE THREAD

**Issue by lewie** [calimero-project/calimero-core#44]
Hi, 
in calimero 2.3, I had to add my own [LogAdapter](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/logging/LogAdapter.java#L29) to the LogManager to get logging:
[LogManager.getManager().addWriter(null, logAdapter);](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXActivator.java#L34)

Now, in calimero 2.4 there are no LogManager, LogWriter anymore. 

Does calimero no longer need a LogAdapter?
Or how should I get logging?

Thank You!

**Comment by calimero-project** [comment]
calimero now logs via the slf4j.
