### ISSUE TITLE
Build error on windows: unmappable character for encoding Cp1252

### ISSUE THREAD

**Issue by LanCenter2000** [calimero-project/calimero-core#48]
Get this error when build on windows

> Task :compileTestJava
\calimero-core\test\tuwien\auto\calimero\dptxlator\DPTXlatorUtf8Test.java:187: error: unmappable character for encoding Cp1252
  final String signs = "├å├?├æ├ÿ├¢";

possible sollution: add this to build.gradle
compileJava.options.encoding     = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'

**Comment by bmalinowsky** [comment]
Thanks!

**Comment by mvig** [comment]
Thanks!

**Comment by NailStorm** [comment]
Thanks!
