### ISSUE TITLE
feedback notification

### ISSUE THREAD

**Issue by ViorelOnica** [calimero-project/calimero-core#68]
Hello, is there any way to implement a listener over a feedback group address to get notified whenever it changes its value?

**Comment by calimero-project** [comment]
There is no API to individually subscribe to notifications from a _single_ group address. Use a `ProcessListener` together with the example shown in javadoc of that interface.

**Comment by ViorelOnica** [comment]
hmm, I see that in your last release you changed some access modifiers from public to protected
For example, I cannot access KNXNetworkLinkIP constructor anymore or KNXNetworkLinkIP.TUNNELING
