### ISSUE TITLE
Cannot resolve symbol 'tuwien' 

### ISSUE THREAD

**Issue by Sultan91** [calimero-project/calimero-core#71]
when importing "import tuwien.auto.calimero.exception.KNXException;"  from ProcessCommunication.java example code

**Comment by bmalinowsky** [comment]
The introduction repository has different sections which explicitly address required Java/calimero versions. I assume the example you use is for calimero <= 2.3 and Java <= 8.

**Comment by Sultan91** [comment]
Thanks
