### ISSUE TITLE
T_Disconnect telegrams triples bus activity while programming

### ISSUE THREAD

**Issue by lewie** [calimero-project/calimero-core#77]
Hello @bmalinowsky,
we have a bad effect while programming devices with the ETS. 
Please, can you put us on the right track a little? ;-)
T_Disconnect telegrams triples bus activity while programming devices.

Discussion: https://github.com/openhab/openhab2-addons/issues/4238

Thank You!

**Comment by bmalinowsky** [comment]
The disconnects in itself are harmless, but IIRC were meant for a more esoteric condition where client-initiated connections got already closed or addressed by the wrong sender. They become a nuisance in a situation with >1 mgmt clients (of which ETS is one) together in the same mcast group.

I leave this issue open to address it with a less traffic-heavy/polluting send approach.

**Comment by JoveToo** [comment]
@bmalinowsky The result of the extra traffic on the bus was a consistent firmware download failure, not quite harmless.

**Comment by lewie** [comment]
I can really confirm the observation. Depending on the hardware device, the T_Disconnect telegrams bother so much that in many cases, the firmware download fails.

**Comment by bmalinowsky** [comment]
@lewie what happens if you check the compatibility checkbox for slower bus communication in ets? Same result?
