### ISSUE TITLE
Calimero api

### ISSUE THREAD

**Issue by pengzhenkun** [calimero-project/calimero-core#86]
你好，有 Calimero 的 api 文档吗？

**Comment by calimero-project** [comment]
Latest snapshot API doc from snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/com/github/calimero/calimero-core/2.5-SNAPSHOT/calimero-core-2.5-20190430.093719-16-javadoc.jar

Or generate it locally, either using

* Maven: `mvn javadoc:javadoc` (output in directory _target/site_)
* Gradle: `./gradlew javadoc` (output in directory _build/docs_)
