### ISSUE TITLE
Maven artifacts are not deployed on maven central

### ISSUE THREAD

**Issue by FSeidinger** [calimero-project/calimero-core#92]
Dear Calimero Team,

I tried to use your artifacts (calimero-core, calimero-device, and calimero-server) via maven central repository.

Whereas your parent is available for latest version 2.4, calimero-core, calimero-device and calimero-server are only available in version 2.4-rc2.

This is in contrast to the released versions which are all 2.4 on github.

I could download the artifacts from github and install them locally, but this is not the intended way with resolving maven dependencies.

So please release the missing versions on maven central.

Kind regards,

Frank

**Comment by calimero-project** [comment]
Version 2.4 can be downloaded from jcenter, which is also a maven repo. I didn't look into syncing it to maven central.

**Comment by calimero-project** [comment]
I found a manual way to trigger the sync, let's see if they also show up on central.

**Comment by FSeidinger** [comment]
That did the trick! Many thanks. I will cose the issue then.
