### ISSUE TITLE
Map of pending sync requests does not handle sync.res on broadcast

### ISSUE THREAD

**Issue by nanosonde** [calimero-project/calimero-core#94]
https://github.com/calimero-project/calimero-core/blob/3af5ad319597650fe200c0f8c0f5d55cbcb002b7/src/tuwien/auto/calimero/internal/SecureApplicationLayer.java#L356

https://github.com/calimero-project/calimero-core/blob/3af5ad319597650fe200c0f8c0f5d55cbcb002b7/src/tuwien/auto/calimero/internal/SecureApplicationLayer.java#L705_L709

The map should have a key of class KnxAddress to store both: IA an GA

In case we need to send a sync.res on broadcast we have a dstAddr of 0 and type GA.
This could then also be stored in the map, when the receiveSyncRequest stashes the challenge.

Sending sync.res on broadcast becomes necessary, if the initial programming of the IA is necessary as there is no IA yet and AppLayer-Services to set the IA only run on broadcast comm mode.

Remark: Using the stack as a device, not from the perspective of a PC client.

**Comment by bmalinowsky** [comment]
Sync broadcasts are handled on a more general basis for some time now, which should also mitigate this. Reopen if there are further issues.
