### ISSUE TITLE
Performance over IP

### ISSUE THREAD

**Issue by scholzi100** [calimero-project/calimero-core#98]
Hi, im currently looking around in the Java/KNX world. 

Are there any statistics about IP throughput of this project against any real system?

**Comment by bmalinowsky** [comment]
Hi, not that I know (at least how I understand it from your question).
In typical installations, KNX communication is upper bounded by the TP/PL/RF medium and dead slow compared to IP.

**Comment by scholzi100** [comment]
Any suggestions on how to generate such metrics from the core project?

**Comment by bmalinowsky** [comment]
You can use wireshark, it has a knx filter and supports some simple statistics.
