### ISSUE TITLE
KNX IoT integration v1

### ISSUE THREAD

**Issue by scholzi100** [calimero-project/calimero-core#99]
Recently KNX IoT v1 Standard got published. Are there any plans for integration in calimero? 

It defines a REST protocol to be implemented by some gateway on the bus, providing integration to 3rd applications. It looks quite big, including XML and JSON variants over HTTP and WebSocket authenticated by OAuth.

Referral links: 
- https://schema.knx.org/
- https://schema.knx.org/AN198.pdf
- https://schema.knx.org/2020/api/v1?visualisation=swagger

**Comment by bmalinowsky** [comment]
It's currently evaluated, but no definitive plans. Also depends how it's adopted by manufacturers.

**Comment by bmalinowsky** [comment]
Neither an issue, RFE, nor contribution.
